'use client';

import { useMemo, useState } from 'react';

type Resource = { name: string; value: number; min: number; max: number; unit: string };
type Constraint = { name: string; value: string };
type Sector = {
  id: string;
  icon: string;
  name: string;
  desc: string;
  resources: Resource[];
  constraints: Constraint[];
  priorities: { name: string; value: number }[];
  metrics: { name: string; base: number }[];
  insight: string;
  recommendation: string;
};
type Scenario = {
  score: number;
  metrics: number[];
  resources: number[];
  priorities: number[];
  constraints: string[];
  label: string;
  timestamp: string;
};
type View = 'workspace' | 'history' | 'tradeoff' | 'debate';

const sectors: Sector[] = [
  { id:'health', icon:'◉', name:'Healthcare', desc:'Balance clinical capacity, staffing, equipment and patient outcomes under real-world constraints.', resources:[{name:'Doctors',value:42,min:10,max:80,unit:'staff'},{name:'Nurses',value:85,min:20,max:160,unit:'staff'},{name:'Beds',value:120,min:40,max:250,unit:'beds'},{name:'Budget',value:50,min:10,max:100,unit:'₹L'}], constraints:[{name:'Emergency reserve',value:'20%'},{name:'Max staff hours',value:'48 hrs/week'},{name:'Bed capacity',value:'120 beds'}], priorities:[{name:'Patient care',value:90},{name:'Response time',value:85},{name:'Risk reduction',value:90},{name:'Cost efficiency',value:70}], metrics:[{name:'Patient capacity',base:92},{name:'Response time',base:88},{name:'Cost efficiency',base:78},{name:'Operational risk',base:26}], insight:'Nursing coverage is the current bottleneck. The model weighs staffing against patient capacity, response time and operational risk.', recommendation:'Protect nursing capacity first. If budget must fall, reduce non-critical equipment spend before frontline staffing.' },
  { id:'agri', icon:'✦', name:'Agriculture', desc:'Optimize land, water, labour and inputs while balancing yield, profitability and sustainability.', resources:[{name:'Land',value:500,min:100,max:1000,unit:'acres'},{name:'Water',value:70,min:20,max:100,unit:'%'},{name:'Labour',value:48,min:10,max:100,unit:'workers'},{name:'Budget',value:32,min:5,max:80,unit:'₹L'}], constraints:[{name:'Water availability',value:'70%'},{name:'Season window',value:'120 days'},{name:'Land ceiling',value:'500 acres'}], priorities:[{name:'Yield',value:90},{name:'Profit',value:80},{name:'Water efficiency',value:85},{name:'Sustainability',value:75}], metrics:[{name:'Expected yield',base:86},{name:'Profitability',base:81},{name:'Water efficiency',base:74},{name:'Crop risk',base:31}], insight:'Water availability has the strongest influence on yield. Labour becomes the next constraint once irrigation is stabilized.', recommendation:'Maintain a water buffer and target labour toward irrigation and high-value crop stages.' },
  { id:'university', icon:'⌘', name:'University & Faculty', desc:'Plan faculty, classrooms and teaching capacity around student demand, workload and course coverage.', resources:[{name:'Faculty',value:80,min:30,max:150,unit:'staff'},{name:'Classrooms',value:42,min:15,max:80,unit:'rooms'},{name:'Labs',value:16,min:5,max:40,unit:'labs'},{name:'Budget',value:40,min:10,max:100,unit:'₹L'}], constraints:[{name:'Max faculty load',value:'18 hrs/week'},{name:'Room capacity',value:'60 students'},{name:'Timetable',value:'6 days/week'}], priorities:[{name:'Course coverage',value:92},{name:'Faculty wellbeing',value:80},{name:'Student experience',value:88},{name:'Cost efficiency',value:65}], metrics:[{name:'Course coverage',base:94},{name:'Student experience',base:86},{name:'Faculty utilization',base:82},{name:'Planning risk',base:22}], insight:'Faculty availability drives course coverage. Classroom capacity matters most when student demand spikes above the timetable baseline.', recommendation:'Preserve a faculty buffer before adding rooms. Reallocate teaching loads to cover bottleneck courses.' },
  { id:'banking', icon:'◇', name:'Banking & Finance', desc:'Balance capital allocation, liquidity, return and risk exposure across financial priorities.', resources:[{name:'Capital',value:80,min:20,max:150,unit:'₹Cr'},{name:'Liquidity',value:35,min:10,max:80,unit:'₹Cr'},{name:'Loan pool',value:55,min:10,max:100,unit:'₹Cr'},{name:'Advisors',value:24,min:5,max:50,unit:'staff'}], constraints:[{name:'Liquidity floor',value:'₹25Cr'},{name:'Risk exposure',value:'≤ 35%'},{name:'Capital reserve',value:'15%'}], priorities:[{name:'Return',value:88},{name:'Risk',value:90},{name:'Liquidity',value:82},{name:'Growth',value:72}], metrics:[{name:'Expected return',base:84},{name:'Liquidity health',base:91},{name:'Risk exposure',base:29},{name:'Growth potential',base:76}], insight:'Liquidity is treated as a hard guardrail. Higher-return allocation is only rewarded while risk and reserve constraints remain healthy.', recommendation:'Increase productive allocation gradually, but preserve the liquidity floor and reserve buffer.' },
  { id:'project', icon:'▦', name:'Project Management', desc:'Simulate workforce, budget and schedule decisions while protecting delivery quality and deadline confidence.', resources:[{name:'Developers',value:24,min:5,max:60,unit:'people'},{name:'Designers',value:8,min:2,max:20,unit:'people'},{name:'Budget',value:45,min:10,max:100,unit:'₹L'},{name:'Time',value:12,min:4,max:30,unit:'weeks'}], constraints:[{name:'Deadline',value:'12 weeks'},{name:'Team capacity',value:'40 hrs/week'},{name:'Budget ceiling',value:'₹50L'}], priorities:[{name:'Delivery speed',value:90},{name:'Quality',value:88},{name:'Cost',value:70},{name:'Risk',value:82}], metrics:[{name:'Deadline confidence',base:89},{name:'Quality',base:91},{name:'Budget efficiency',base:79},{name:'Delivery risk',base:24}], insight:'Developer capacity is the dominant schedule lever. Cutting team size saves cost quickly but compounds deadline and quality risk.', recommendation:'Avoid cutting critical engineering capacity near the deadline; trade scope before cutting the bottleneck resource.' },
  { id:'allocation', icon:'⊞', name:'Resource Allocation', desc:'A flexible decision canvas for allocating scarce resources across competing objectives and constraints.', resources:[{name:'Resource A',value:60,min:10,max:100,unit:'units'},{name:'Resource B',value:40,min:10,max:100,unit:'units'},{name:'Budget',value:50,min:10,max:100,unit:'₹L'},{name:'Capacity',value:75,min:20,max:100,unit:'%'}], constraints:[{name:'Budget ceiling',value:'₹50L'},{name:'Capacity floor',value:'60%'},{name:'Reserve',value:'15%'}], priorities:[{name:'Performance',value:90},{name:'Efficiency',value:85},{name:'Risk',value:80},{name:'Flexibility',value:75}], metrics:[{name:'Performance',base:88},{name:'Efficiency',base:84},{name:'Resource utilization',base:81},{name:'Allocation risk',base:27}], insight:'The model looks for bottlenecks and diminishing returns rather than maximizing a single resource in isolation.', recommendation:'Keep a reserve, fund the highest-impact bottleneck and avoid over-allocation after marginal gains flatten.' }
];

const clamp = (n:number,a:number,b:number) => Math.max(a, Math.min(b,n));
const numericConstraint = (value:string) => { const m = value.replace(/,/g,'').match(/-?\d+(?:\.\d+)?/); return m ? Number(m[0]) : 0; };

function analyze(sector:Sector, resources:number[], priorities:number[], constraints:string[], previous?:Scenario) {
  const baseline = sector.resources.map(r => r.value);
  const ratios = resources.map((v,i) => v / baseline[i]);
  const avg = ratios.reduce((a,b) => a+b,0) / ratios.length;
  const spread = Math.max(...ratios) - Math.min(...ratios);
  const pAvg = priorities.reduce((a,b) => a+b,0) / priorities.length;
  const cNums = constraints.map(numericConstraint);
  const baseC = sector.constraints.map(c => numericConstraint(c.value));
  const constraintShift = baseC.length ? cNums.reduce((sum,v,i) => sum + (baseC[i] ? Math.abs(v-baseC[i]) / Math.max(baseC[i],1) : 0),0) / baseC.length : 0;
  const score = clamp(Math.round(72 + avg*13 + pAvg*.08 - spread*9 - constraintShift*6),45,97);
  const metrics = sector.metrics.map((m,i) => clamp(Math.round(m.base + (avg-1)*18 + (ratios[i%ratios.length]-1)*12 - spread*5 - constraintShift*3),5,99));
  const delta = previous ? score - previous.score : 0;
  return {score, metrics, delta};
}

function ScoreTrend({history,current}:{history:Scenario[];current:number}) {
  const values = history.length ? history.map(h=>h.score) : [current];
  const width=520, height=190, padX=28, padY=24;
  const min=Math.max(40,Math.min(...values)-8), max=Math.min(100,Math.max(...values)+8), range=Math.max(1,max-min);
  const points=values.map((v,i)=>{const x=values.length===1?width/2:padX+i*(width-padX*2)/(values.length-1);const y=height-padY-(v-min)/range*(height-padY*2);return `${x},${y}`;}).join(' ');
  return <div className="linechart"><div className="chartaxis"><span>{max}</span><span>{Math.round((max+min)/2)}</span><span>{min}</span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Decision score trend"><line x1="28" y1="24" x2="28" y2="166" className="gridline"/><line x1="28" y1="166" x2="492" y2="166" className="gridline"/><line x1="28" y1="95" x2="492" y2="95" className="gridline"/><polyline points={points} className="trendline" fill="none"/>{values.map((v,i)=>{const x=values.length===1?width/2:padX+i*(width-padX*2)/(values.length-1);const y=height-padY-(v-min)/range*(height-padY*2);return <circle key={i} cx={x} cy={y} r="5" className="trenddot"/>;})}</svg><div className="chartlabels">{values.map((_,i)=><span key={i}>{history.length?history[i].label:'Live'}</span>)}</div></div>;
}

export default function Home() {
  const [selected,setSelected]=useState<Sector|null>(null);
  const [resources,setResources]=useState<number[]>([]);
  const [priorities,setPriorities]=useState<number[]>([]);
  const [constraints,setConstraints]=useState<string[]>([]);
  const [history,setHistory]=useState<Scenario[]>([]);
  const [simulated,setSimulated]=useState(false);
  const [view,setView]=useState<View>('workspace');
  const [tradeResource,setTradeResource]=useState(0);
  const [debateMode,setDebateMode]=useState<'support'|'challenge'>('challenge');

  const current=useMemo(()=>selected?analyze(selected,resources,priorities,constraints,history.at(-1)):null,[selected,resources,priorities,constraints,history]);
  const previous=history.at(-1);
  const resourceSensitivity=useMemo(()=>{
    if(!selected) return [] as {name:string;unit:string;up:number;down:number;impact:number}[];
    return selected.resources.map((r,i)=>{
      const up=[...resources], down=[...resources];
      up[i]=clamp(up[i]+(r.max-r.min)*.1,r.min,r.max);
      down[i]=clamp(down[i]-(r.max-r.min)*.1,r.min,r.max);
      const upScore=analyze(selected,up,priorities,constraints).score;
      const downScore=analyze(selected,down,priorities,constraints).score;
      const base=current?.score||0;
      return {name:r.name,unit:r.unit,up:Math.round(upScore-base),down:Math.round(downScore-base),impact:Math.abs(upScore-downScore)};
    });
  },[selected,resources,priorities,constraints,current?.score]);

  const start=(s:Sector)=>{setSelected(s);setResources(s.resources.map(r=>r.value));setPriorities(s.priorities.map(p=>p.value));setConstraints(s.constraints.map(c=>c.value));setHistory([]);setSimulated(false);setView('workspace');setTradeResource(0);};
  const run=()=>{if(!selected||!current)return;setHistory(h=>[...h,{score:current.score,metrics:current.metrics,resources:[...resources],priorities:[...priorities],constraints:[...constraints],label:`Scenario ${String(h.length+1).padStart(2,'0')}`,timestamp:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}]);setSimulated(true);};
  const reset=()=>{if(!selected)return;setResources(selected.resources.map(r=>r.value));setPriorities(selected.priorities.map(p=>p.value));setConstraints(selected.constraints.map(c=>c.value));setSimulated(false);};
  const loadScenario=(s:Scenario)=>{setResources([...s.resources]);setPriorities([...s.priorities]);setConstraints([...s.constraints]);setSimulated(true);setView('workspace');};

  if(!selected) return <main className="app"><header className="topbar"><div className="brand"><div className="logo">DS</div><div><strong>DecisionSphere</strong><small>Scenario intelligence</small></div></div><div className="topmeta"><span className="live"><i className="dot"/> Decision engine ready</span><span className="pill">6 decision domains</span></div></header><div className="main landing"><div className="hero"><div><div className="eyebrow">AI-powered decision simulation</div><h1>Make decisions before<br/><em>they become consequences.</em></h1><p>Model resources, constraints and priorities. Compare scenarios, visualize trade-offs and let the decision agent challenge your assumptions.</p></div><div className="hero-badge"><div className="orbit">DS</div><span>SIMULATE<br/><b>COMPARE · DEBATE · DECIDE</b></span></div></div><div className="card domain-card"><div className="cardtitle"><div><h3>Select a decision domain</h3><p>Each sector uses its own variables while sharing one intelligence layer.</p></div><span>START WITH A SCENARIO →</span></div><div className="sector-grid">{sectors.map(s=><button className="sector" key={s.id} onClick={()=>start(s)}><div className="sectoricon">{s.icon}</div><h3>{s.name}</h3><p>{s.desc}</p><div className="sectorfoot"><span>Open workspace</span><b>↗</b></div></button>)}</div></div><div className="landing-strip"><div><b>01</b><span>Adjust assumptions</span></div><div><b>02</b><span>Simulate outcomes</span></div><div><b>03</b><span>Compare trade-offs</span></div><div><b>04</b><span>Debate the decision</span></div></div></div></main>;

  const debateText=previous ? (debateMode==='challenge' ? `Challenge: Scenario ${previous.label} scored ${previous.score}/100. The current scenario scores ${current?.score}/100. Check the strongest changed lever and whether the edited constraints still represent reality.` : `Support: the current scenario scores ${current?.score}/100 versus ${previous.score}/100 previously. The change is directionally supported by the model, provided the new constraints are valid and the resource assumptions are achievable.`) : 'Run at least two scenarios to make the decision debate evidence-based.';
  const strongest=resourceSensitivity.length ? [...resourceSensitivity].sort((a,b)=>b.impact-a.impact)[0] : null;

  return <main className="app">
    <header className="topbar"><div className="brand"><div className="logo">DS</div><div><strong>DecisionSphere</strong><small>Scenario intelligence</small></div></div><div className="topmeta"><span className="live"><i className="dot"/> Engine active</span><span className="pill">{selected.name}</span><span className="pill">{history.length} scenarios</span></div></header>
    <div className="shell">
      <aside className="sidebar"><button className="back" onClick={()=>setSelected(null)}>← All sectors</button><div className="sector-mini"><div className="sector-mini-icon">{selected.icon}</div><div><strong>{selected.name}</strong><small>Decision workspace</small></div></div><div className="side-label">Analysis</div>
        {([['workspace','◈','Decision workspace'],['history','⌁','Scenario history'],['tradeoff','◌','Trade-off explorer'],['debate','✦','AI decision debate']] as [View,string,string][]).map(([v,icon,label])=><button key={v} className={`navitem ${view===v?'active':''}`} onClick={()=>setView(v)}><span>{icon}</span>{label}{v==='history'&&<b>{history.length}</b>}</button>)}
        <div className="side-note"><strong>How it works</strong><p>Edit resources, priorities and constraints. Run a scenario to retain it as evidence. Use the analysis tabs to inspect history, trade-offs and the decision debate.</p></div><div className="side-footer">DECISIONSPHERE v1.0<br/>Explainable scenario intelligence</div>
      </aside>
      <section className="main">
        <div className="hero"><div><div className="eyebrow">{selected.name} · {view==='workspace'?'decision workspace':view==='history'?'scenario history':view==='tradeoff'?'trade-off explorer':'AI decision debate'}</div><h1>{view==='workspace'?'Scenario Intelligence':view==='history'?'Scenario History':view==='tradeoff'?'Trade-off Explorer':'AI Decision Debate'}</h1><p>{view==='workspace'?'Adjust the decision levers. Run the model. Every scenario becomes evidence for the next decision.':view==='history'?'Review, compare and reload scenarios you have already simulated.':view==='tradeoff'?'Test which resource has the strongest effect on your decision score.':'Let the decision agent support or challenge the current conclusion using scenario evidence.'}</p></div><div className="actions"><button className="btn" onClick={reset}>Reset</button>{view==='workspace'&&<button className="btn primary" onClick={run}>Run simulation ↗</button>}</div></div>

        {view==='workspace' && <>
          <div className="metrics"><div className="metric accent"><div className="metric-head"><span>Decision score</span><span>{current?.delta&&current.delta>=0?'+':''}{current?.delta||0}</span></div><div className="metric-value">{current?.score}<small>/100</small></div><div className="trend up">{history.length?'Compared with previous':'Baseline model'}</div></div><div className="metric"><div className="metric-head"><span>Scenario status</span><span className="status-dot">●</span></div><div className="metric-value">{simulated?'Analyzed':'Draft'}</div><div className="trend">Inputs validated</div></div><div className="metric"><div className="metric-head"><span>Scenario memory</span><span>{history.length}</span></div><div className="metric-value">{history.length?'Active':'Ready'}</div><div className="trend">Previous output retained</div></div><div className="metric"><div className="metric-head"><span>Editable model</span><span>✓</span></div><div className="metric-value">Live</div><div className="trend">Resources + constraints</div></div></div>
          <div className="workspace-grid"><div className="card controls"><div className="cardtitle"><div><h3>Decision levers</h3><p>All fields below are editable. Changes update the model instantly.</p></div><span>LIVE INPUTS</span></div><div className="control-section"><h4>Resources</h4>{selected.resources.map((r,i)=><div className="slider-row" key={r.name}><div className="slider-head"><label>{r.name}</label><strong>{resources[i]} <small>{r.unit}</small></strong></div><input type="range" min={r.min} max={r.max} value={resources[i]??r.value} onChange={e=>setResources(a=>a.map((x,j)=>j===i?Number(e.target.value):x))}/><div className="range-labels"><span>{r.min}</span><span>{r.max}</span></div></div>)}</div><div className="control-section"><h4>Priorities</h4>{selected.priorities.map((p,i)=><div className="slider-row" key={p.name}><div className="slider-head"><label>{p.name}</label><strong>{priorities[i]}%</strong></div><input type="range" min="0" max="100" value={priorities[i]??p.value} onChange={e=>setPriorities(a=>a.map((x,j)=>j===i?Number(e.target.value):x))}/></div>)}</div></div>
            <div className="card constraints"><div className="cardtitle"><div><h3>Constraints</h3><p>Previously fixed assumptions are now user-editable.</p></div><span>EDITABLE</span></div>{selected.constraints.map((c,i)=><div className="constraint-row" key={c.name}><div><strong>{c.name}</strong><small>Model guardrail</small></div><input value={constraints[i]??c.value} onChange={e=>setConstraints(a=>a.map((x,j)=>j===i?e.target.value:x))} aria-label={`${c.name} constraint`}/></div>)}<div className="constraint-tip">Tip: edit values such as <b>25%</b>, <b>50 hrs/week</b> or <b>₹60L</b>. The model includes the change in the next score.</div></div></div>
          <div className="analytics-grid"><div className="card chart-card"><div className="cardtitle"><div><h3>Decision Score Trajectory</h3><p>Recorded scenario outcomes</p></div><span>{history.length} RUNS</span></div><ScoreTrend history={history} current={current?.score||0}/></div><div className="card"><div className="cardtitle"><div><h3>Outcome dimensions</h3><p>Live model response</p></div></div><div className="bars">{selected.metrics.map((m,i)=><div className="barrow" key={m.name}><div><span>{m.name}</span><b>{current?.metrics[i]}</b></div><div className="bartrack"><i style={{width:`${current?.metrics[i]??0}%`}}/></div></div>)}</div></div></div>
          <div className="insight-grid"><div className="card insight"><span className="label">MODEL INSIGHT</span><h3>{selected.insight}</h3></div><div className="card recommendation"><span className="label">RECOMMENDATION</span><h3>{selected.recommendation}</h3></div></div>
        </>}

        {view==='history' && <><div className="card full-card"><div className="cardtitle"><div><h3>Saved scenarios</h3><p>Each simulation is stored locally for comparison and can be loaded back into the workspace.</p></div><span>{history.length} SCENARIOS</span></div>{history.length===0?<div className="empty"><div>⌁</div><h3>No scenarios yet</h3><p>Adjust the model and click <b>Run simulation</b>. Your first run will appear here.</p><button className="btn primary" onClick={()=>setView('workspace')}>Open workspace</button></div>:<div className="history-list">{history.map((s,i)=><div className={`history-item ${i===history.length-1?'latest':''}`} key={`${s.label}-${i}`}><div className="history-number">{String(i+1).padStart(2,'0')}</div><div className="history-main"><div><strong>{s.label}</strong>{i===history.length-1&&<span className="latest-tag">LATEST</span>}</div><p>{s.timestamp} · {s.resources.length} resources · {s.constraints.length} constraints</p></div><div className="history-score"><b>{s.score}</b><small>/100</small></div><button className="btn" onClick={()=>loadScenario(s)}>Load</button></div>)}</div>}</div><div className="card chart-card history-chart"><div className="cardtitle"><div><h3>Scenario history graph</h3><p>Score progression across saved runs</p></div></div><ScoreTrend history={history} current={current?.score||0}/></div></>}

        {view==='tradeoff' && <div className="tradeoff-layout"><div className="card full-card"><div className="cardtitle"><div><h3>Explore one lever</h3><p>Choose a resource and see how a controlled ±10% change affects the score.</p></div><span>SENSITIVITY</span></div><div className="trade-tabs">{selected.resources.map((r,i)=><button className={tradeResource===i?'selected':''} key={r.name} onClick={()=>setTradeResource(i)}>{r.name}</button>)}</div>{resourceSensitivity[tradeResource]&&<div className="sensitivity"><div className="sensitivity-center"><span>Current</span><strong>{current?.score}</strong><small>/100</small></div><div className="impact-card"><span>Increase 10%</span><b className={resourceSensitivity[tradeResource].up>=0?'positive':'negative'}>{resourceSensitivity[tradeResource].up>=0?'+':''}{resourceSensitivity[tradeResource].up}</b><small>score points</small></div><div className="impact-card"><span>Decrease 10%</span><b className={resourceSensitivity[tradeResource].down>=0?'positive':'negative'}>{resourceSensitivity[tradeResource].down>=0?'+':''}{resourceSensitivity[tradeResource].down}</b><small>score points</small></div></div>}<div className="sensitivity-table"><div><span>Resource</span><span>Increase</span><span>Decrease</span><span>Impact range</span></div>{resourceSensitivity.map(r=><div key={r.name}><b>{r.name}</b><span className={r.up>=0?'positive':'negative'}>{r.up>=0?'+':''}{r.up}</span><span className={r.down>=0?'positive':'negative'}>{r.down>=0?'+':''}{r.down}</span><strong>{r.impact}</strong></div>)}</div></div><div className="card full-card"><div className="cardtitle"><div><h3>Priority balance</h3><p>Current weight assigned to each objective</p></div></div><div className="priority-grid">{selected.priorities.map((p,i)=><div className="priority-card" key={p.name}><span>{p.name}</span><b>{priorities[i]}%</b><div className="bartrack"><i style={{width:`${priorities[i]}%`}}/></div></div>)}</div></div></div>}

        {view==='debate' && <div className="debate-layout"><div className="card debate-card"><div className="cardtitle"><div><h3>AI Decision Debate</h3><p>The agent deliberately tests both sides of the conclusion.</p></div><span>EXPLAINABLE</span></div><div className="debate-switch"><button className={debateMode==='challenge'?'selected':''} onClick={()=>setDebateMode('challenge')}>Challenge decision</button><button className={debateMode==='support'?'selected':''} onClick={()=>setDebateMode('support')}>Support decision</button></div><div className="debate-message"><div className="agent">✦</div><div><span>{debateMode==='challenge'?'CRITICAL REVIEW':'EVIDENCE REVIEW'}</span><h3>{debateText}</h3></div></div>{previous&&<div className="compare-box"><div><span>Previous</span><b>{previous.score}/100</b></div><div className="compare-arrow">→</div><div><span>Current</span><b>{current?.score}/100</b></div><div className={`delta ${current&&current.score>=previous.score?'positive':'negative'}`}>{current&&current.score-previous.score>=0?'+':''}{current&&current.score-previous.score}</div></div>}<div className="debate-prompts"><div><b>1</b><span>Which assumption changed most?</span><strong>{strongest?.name||'Run a scenario'}</strong></div><div><b>2</b><span>Are the new constraints credible?</span><strong>{constraints.some((c,i)=>selected.constraints[i]&&c!==selected.constraints[i].value)?'Changed — review':'Unchanged'}</strong></div><div><b>3</b><span>What should be protected?</span><strong>{strongest?.name||selected.resources[0].name}</strong></div></div></div><div className="card debate-side"><span className="label">DECISION AGENT</span><h3>Use debate after at least two runs</h3><p>The agent compares saved evidence rather than pretending to have certainty. Edit assumptions, run another scenario, then switch between challenge and support.</p><button className="btn primary" onClick={()=>setView('history')}>Review scenario evidence →</button></div></div>}
      </section>
    </div>
  </main>;
}
